export const productConstant = {
  CREATE_REQUEST: "PRODUCT_CREATE_REQUEST",
  CREATE_SUCCESS: "CREATE_CREATE_SUCCESS",
  CREATE_FAILURE: "CREATE_CREATE_FAILURE",

  GET_REQUEST: "PRODUCT_GET_REQUEST",
  GET_SUCCESS: "PRODUCT_GET_SUCCESS",
  GET_FAILURE: "PRODUCT_GET_FAILURE",
};
