export const productConstant = {
  CREATE_REQUEST: "PRODUCT_CREATE_REQUEST",
  CREATE_SUCCESS: "CREATE_CREATE_SUCCESS",
  CREATE_FAILURE: "CREATE_CREATE_FAILURE",

  GET_REQUEST: "PRODUCT_GET_REQUEST",
  GET_SUCCESS: "PRODUCT_GET_SUCCESS",
  GET_FAILURE: "PRODUCT_GET_FAILURE",

  GET_ALL_REQUEST: "PRODUCT_GET_ALL_REQUEST",
  GET_ALL_SUCCESS: "PRODUCT_GET_ALL_SUCCESS",
  GET_ALL_FAILURE: "PRODUCT_GET_ALL_FAILURE",

  DELETE_REQUEST: "PRODUCT_DELETE_REQUEST",
  DELETE_SUCCESS: "PRODUCT_DELETE_SUCCESS",
  DELETE_FAILURE: "PRODUCT_DELETE_FAILURE",

  GET_ALL_USER_PRODUCTS_REQUEST: "GET_ALL_USER_PRODUCTS_REQUEST:",
  GET_ALL_USER_PRODUCTS_SUCCESS: "GET_ALL_USER_PRODUCTS_SUCCESS:",
  GET_ALL_USER_PRODUCTS_FAILURE: "GET_ALL_USER_PRODUCTS_FAILURE:",

  GET_TOTAL_PAGES: "GET_TOTAL_PAGES",
};
